### ISSUE TITLE
Use click/argparse for options

### ISSUE THREAD

**Issue by mzfr** [Ugtan/FideStats#1]
currently the code is quite dirty because of the presence of so many if and loops it would be better if you can use [click](http://click.pocoo.org/5/) or argparse for options.

**Comment by Ugtan** [comment]
I have to agree with you on this, The code is somehow repetitive which kinda takes away the feel of the script and is pretty much unnecessary. But Surely will be working on these things as well in the future and will try to incorporate argparse in the script as well.
